name: nest_flutter
description: Flutter integration for Nest Dart - bringing dependency injection and modular architecture to Flutter applications.
version: 0.1.1
resolution: workspace
homepage: https://chornthorn.github.io/nest-dart
repository: https://github.com/chornthorn/nest-dart
issue_tracker: https://github.com/chornthorn/nest-dart/issues
documentation: https://chornthorn.github.io/nest-dart/flutter-guide

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  nest_core: ^0.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
