name: nest_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  nest_core:
    path: ../../packages/nest_core

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
