name: nest_frog
description: Dart Frog integration for Nest Dart - bringing dependency injection and modular architecture to Dart Frog backend applications.
version: 0.1.2
resolution: workspace
homepage: https://chornthorn.github.io/nest-dart
repository: https://github.com/chornthorn/nest-dart
issue_tracker: https://github.com/chornthorn/nest-dart/issues
documentation: https://chornthorn.github.io/nest-dart/frog-guide

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  nest_core: ^0.1.1
  dart_frog: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
