name: nest_frog_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  dart_frog: ^1.1.0
  nest_core:
    path: ../../packages/nest_core
  nest_frog:
    path: ../../packages/nest_frog
  sqlite3: ^2.8.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
