name: nest_core
description: A starting point for Dart libraries or applications.
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  get_it: ^8.1.0
  logger: ^2.6.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
