name: nest_core
description: Core dependency injection and module system for Nest Dart - a NestJS-inspired framework for building modular Dart applications.
version: 0.1.1
resolution: workspace
homepage: https://chornthorn.github.io/nest-dart
repository: https://github.com/chornthorn/nest-dart
issue_tracker: https://github.com/chornthorn/nest-dart/issues
documentation: https://chornthorn.github.io/nest-dart/core-guide

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  get_it: ^8.2.0
  logger: ^2.6.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
